/*
 * Copyright (c) 2012, Intel Corporation.
 *
 * This program is licensed under the terms and conditions of the
 * Apache License, version 2.0.  The full text of the Apache License is at
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 */

var LOCALE = {
  "select_items": "Select items.",
  "go_back_and_select_list_first": "Go back and Select list first.",
  "items_saved_in_the": "Items saved in the ",
  "list": "list ",
  "database_error": "Database Error.",
  "item_name_is_empty": "Item name is empty.",
  "list_is_empty": "List is empty.",
  "already_exists_in_the": "already exists in the ",
  "do_you_want_to_add_anyway": " list. Do you want to add this item anyway?",
  "store_name_is_empty": "Store name is empty.",
  "store": "Store ",
  "already_exists_define_other_name": " already exists.\n Please define another name.",
  "list_name_is_empty": "List name is empty. ",
  "list_color_is_empty": "List color is empty.",
  "invalid_list_data": "Invalid List Data!",
  "no_store": "(no store)",
  "no_list": "(no list)",
  "create_new_list": "Create New List",
  "name_of_list": "Name of List:",
  "choose_color": "Choose a Color to Define Your List:",
  "item_type": "Choose a Color:",
  "edit_list": "Edit List",
  "view_all":  "View All",
  "all_my_favorites": "All My Favorites",
  "add_new_list": "Add New List",
  "add_new_store": "Add New Store",
  "add": "Add",
  "add_store": "Add Store",
  "edit_store": "Edit Store", 
  "storename_label": "Name:",
  "save_text": "Save",
  "info_text": "Info",
  "ok_text": "Ok",
  "question_text": "Question",
  "yes_text": "Yes",
  "no_text": "No",
  "options_title": "Options",
  "edit_item": "Edit item",
  "move_item": "Move item to",
  "delete_item": "Delete item",
  "edit_list_2": "Edit list",
  "uncheck_all_list_items": "Uncheck all list items",
  "move_all_list_items": "Move all list items to",
  "remove_all_list_items": "Remove all list items",
  "delete_list": "Delete list",
  "change_name": "Change name",
  "uncheck_all_store_names": "Uncheck all store items",
  "move_all_store_items_to": "Move all store items to",
  "remove_all_store_items": "Remove all store items",
  "delete_store": "Delete store",
  "sortby_title": "Sort by",
  "sortby_alphabet": "Alphabetically",
  "sortby_store": "Store",
  "sortby_type": "Type",
  "sortby_bought_status": "Bought status",
  "listselection_title": "Select List",
  "storeselection_title": "Select Store",
  "addfromfavorites_view_title": "Add from My Favorites",
  "enter_keyword": "Enter keyword",
  "favorites_item_list_label": "List:",
  "favorites_item_store_label": "Store:",
  "add_one_item": "Add One Item",
  "set_store": "Set Store",
  "some_selected_items_already_in": "Some of the selected items are already in ",
  "add_item": "Add item",
  "edit_item": "Edit item",
  "item_name_label": "Item Name:",
  "item_list_label": "List:",
  "item_type_label": "Item Type:",
  "item_store_label": "Store:",
  "photo_label": "Photo:",
  "add_photo_label": "Tap to add Photo",
  "add_from_my_favorites": "Add from My Faves",
  "delete_text": "Delete",
  "items_saved_in": "Items saved in the ",
  "list_dot": " list.",
  "lists_not_available": "Lists not available. First create a new list from Lists View.",
  "stores_not_available": "Stores not available. First create a new store from Stores View.",
  "photo_source": "Photo Source",
  "take_from_camera": "Take from camera",
  "select_from_gallery": "Select from gallery",
  "gallery_launch_failed": "Gallery launch failed.",
  "error_adding_photo": "Error while adding photo.",
  "empty_list": "Empty !",
  "change_text": "Change",
  "photo_capture_not_supported": "Photo capture is not supported.",
  "photo_saving_failed_do_you_want_to_save": "Photo saving failed. Do you want to save item ?",
  "image_data_reading_failed": "Reading image data failed."
};
